name: ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - ffmpeg
  - ffmpeg-python
  - pillow
  - tqdm
  - pyyaml
  - matplotlib-base
  - pytest
  - pip:
      - torch==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - torchaudio==2.8.0+cu128
      - typing-extensions==4.13.1
      - --extra-index-url https://download.pytorch.org/whl/cu128
