# Copy to configs/local.yaml and customize for your machine
data:
  dataset_path: "/abs/path/to/datasets/comma2k19"
  num_workers: 2
train:
  batch_size: 8
  epochs: 10
  window_size: 20
runtime:
  device: mps  # use cuda|cpu|mps depending on your hardware
  log_interval: 1000

